this should avoid running old images

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -82,14 +82,10 @@ jobs:
           name: macro
 
       - name: Build image
-        uses: docker/build-push-action@v7
-        with:
-          context: .
-          tags: cekeh/macro:latest
-          target: production
+        run: docker build --target production -t macro:${{ github.sha }} .
 
-      - name: Health check (run)
-        run: docker run -d --rm -p 8080:8080 -v data:/data --name test cekeh/macro:latest
+      - name: Health check
+        run: docker run -d --rm -p 8080:8080 -v data:/data --name test macro:${{ github.sha }}
 
       - name: Health check (test)
         run: |
@@ -100,19 +96,26 @@ jobs:
                --max-time 3 \
                --fail http://localhost:8080/api/health
 
+      - name: Health check (cleanup)
+        run: docker rm -f test
+
       - name: Login to Docker Hub
         uses: docker/login-action@v4
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
 
-      - name: Push image
+      - name: Build and push image
         id: build_and_push
         uses: docker/build-push-action@v7
         with:
           tags: cekeh/macro:latest
           target: production
           push: true
+
+      # - name: Cleanup
+      #   if: always()
+      #   run: docker rm -f test && docker rmi macro:${{ github.sha }} || true
 
   # deploy:
   #   runs-on: ubuntu-latest
